### ISSUE TITLE
Error in TitanRep On Load

### ISSUE THREAD

**Issue by KerynW** [Ivaria/titanrep#4]
I *think* this is an issue starting in TitanRep rather than in TitanPanel itself (but I could be reading it wrong.)  TitanRep isn't loading at all.

1x Titan/TitanUtils.lua:1794: attempt to index local 'self' (a nil value)
[string "@Titan/TitanUtils.lua"]:1794: in function `TitanPanelRightClickMenu_Toggle'
[string "@Titan/Titan.lua"]:597: in function `TitanPanelBarButton_OnClick'
[string "@TitanReputation/TitanReputation.lua"]:176: in function `TitanPanelReputationButton_OnLoad'
[string "*TitanReputation.xml:14_OnLoad"]:1: in function <[string "*TitanReputation.xml:14_OnLoad"]:1>

Locals:
self = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'self' (a nil value)"

**Comment by KerynW** [comment]
Finally went and dug into the code and I think this will fix it... the error is in something labeled a temporary fix, so I commented out those two lines and tried it out.  It has been working perfectly for a week or so, no further errors and all parts appear to be functioning normally.  Here are the lines I removed, starting at line 176 in TitanReputation.lua:

```
    --Temporary Patch for Titan Panel RightClick bug.
    --TitanPanelBarButton_OnClick(Titan_Bar__Display_Bar,"RightButton")   
    --TitanPanelRightClickMenu_Close()
```

**Comment by Ivaria** [comment]
Apologies, I've had no time to look at this since 10.1 launched.

Looks like TitanPanel v7.x changed the frame name and so that call no longer worked.  As you've found I think the workaround is long since no longer needed anyway.
